### ISSUE TITLE
Shamans - Banking sometimes gets stuck on Enter Amount dialog

### ISSUE THREAD

**Issue by alexfaxe** [squire-plugins/bugs#16] opened 2022-09-19 09:33 UTC
most likely related to banking speed vs ping

**Comment by gargslayer101** [comment] 2022-09-19 15:29
Possible duplicate of https://gitlab.com/runemate/community/runemate-client/-/issues/209

**Comment by chadsisson** [comment] 2022-10-10 14:01
https://github.com/squire-plugins/SquirePlugins/commit/16d93bbd422779abacf7a2e44dc62561b23c30ea

**Closed by chadsisson** 2022-10-10 14:01 UTC
Labels: bug, shamans
